name:                availability
version:             0.1.0.0
github:              "re-xyr/availability"
license:             BSD3
author:              "daylily"
maintainer:          "xy.r@outlook.com"
copyright:           "2021 daylily"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/re-xyr/availability#readme>

dependencies:
- base
- mtl
- lens
- generic-lens
- exceptions
- unliftio

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wincomplete-record-updates
- -Widentities
- -O2

library:
  source-dirs: src

tests:
  availability-examples:
    main:                Main.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - availability
    - hspec
    - QuickCheck
    - silently
    default-extensions:
    - DeriveGeneric

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- ConstraintKinds
- DataKinds
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- DerivingVia
- LambdaCase
- MultiParamTypeClasses
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
- UndecidableSuperClasses
