name:                availability
version:             0.1.0.0
github:              "re-xyr/availability"
license:             BSD3
author:              "daylily"
maintainer:          "xy.r@outlook.com"
copyright:           "2021 daylily"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Fast effects for concrete monads
category:            Control

description: |
  Efficient effect system that works with concrete monad types, à la the
  <https://xn--i2r.xn--rhqv96g/2021/09/14/redundant-constraints/ phantom constraint pattern>. Also comes with several 
  standard effects and convenient combinators for deriving them in the existing ecosystem.

dependencies:
- base
- mtl
- lens
- generic-lens
- exceptions
- unliftio

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wincomplete-record-updates
- -Widentities
- -O2

library:
  source-dirs: src

tests:
  availability-examples:
    main:                Main.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - availability
    - hspec
    - QuickCheck
    - silently
    default-extensions:
    - DeriveGeneric

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- ConstraintKinds
- DataKinds
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- DerivingVia
- LambdaCase
- MultiParamTypeClasses
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances
